### ISSUE TITLE
MultiCraft is not open source but claims it is

### ISSUE THREAD

**Issue by Wuzzy2** [MultiCraftProject/MultiCraft#119]
MultiCraft claims it's open source, but this is (sadly) false.

The README states:

“MultiCraft Open Source Project”

and

“MultiCraft is an Open Source sandbox game inspired by Minecraft.”

Even the project logo has “open source” in it.

However, it also states:

“The engine and the game is licensed under LGPLv3 (or higher). Resources games licensed under CC-BY-SA 3.0, unless otherwise stated, and also a bit of proprietary code and resources.”

In other words, **Multicraft is not open source**. The term “open source” implies the program is not proprietary at all (including media), also, a program can not contain any proprietary code (even just a bit) and still call itself “open source”.

See also: https://opensource.org/definition
Note the above definition is not some random crazy fringe opinion, this is the *official* definition of “open source” and very widely accepted in the open source and free software communities.

Please do one of the following:

* Remove all hints of MultiCraft being “open source” as those claims are falsehoods

- or -

* Fix the files with unclear/dubious/proprietary licensing to make the project open source

**Comment by MoNTE48** [comment]
Hey. Thank you for taking the time to evaluate this project!
I would like to clarify. **MultiCraft has always been a completely open project.** We publish all the source code, which was taken from other sources. But you are right in saying that some part is proprietary. I will explain:
1) We have been cooperating with some advertising networks for a long time and we use libraries written personally for our project, which we have no right to publish. Note that we publish all the source code, except for these libraries. For example:
https://github.com/MultiCraftProject/MultiCraft/blob/master/build/android/src/main/java/mobi/MultiCraft/GameActivity.java#L31
https://github.com/MultiCraftProject/MultiCraft/blob/master/build/android/src/main/java/mobi/MultiCraft/MainActivity.java#L432
https://github.com/MultiCraftProject/MultiCraft/blob/master/src/client/clientlauncher.cpp#L39
You can find more examples in the code yourself. As you can see, we published 100% of the open source code.
---
2) The game (mostly) uses free images and fonts with attribution. Also, some images and fonts we **LICENSED** for use **EXCLUSIVELY in this project**. To redeem the rights to these textures, fonts and images would be expensive and not reasonable. If someone wants to take all the changes to MultiCraft completely and create another project, he can write to us and I will indicate which images were purchased from which authors and he can buy permission for their use in his project.
Again, this applies only to graphic images and fonts.
**All source code published here is open and free in accordance with the license attached to it!**

**Comment by MoNTE48** [comment]
I would like to make a clarification. We carefully checked - the source code licensed under LGPLv3.0 and CC-BY-SA 3.0 allows the use of proprietary libraries with it. The absence of these libraries does not in any way affect the operability or functionality of the project. Accordingly, we have the right to add these libraries by patch during the build process.
You can talk to @sfan5, for example. He confirms that we published 100% of the source code of the iOS build, except for the advertising module, which is added during the building process. Very many open source projects operate in the same way as we do: they provide source code, a free version with advertising and a paid version without ads, but with priority support. You can get a version without ads by simply building the source code yourself.

**Comment by Wuzzy2** [comment]
So the binaries you distribute are proprietary, but this repository really is open source?

Did I get this right? Well, according to what you've said, I still have my doubts.

Well, if this repository is 100% open source according to the OSI definition, then this sentence in readme is obviously false and should be fixed:

> The engine and the game is licensed under LGPLv3 (or higher). Resources games licensed under CC-BY-SA 3.0, unless otherwise stated, **and also a bit of proprietary code and resources**.

(emphasis added by me)

> We have been cooperating with some advertising networks for a long time and we use libraries written personally for our project, which we have no right to publish. Note that we publish all the source code, except for these libraries. For example:

So this refers to some disabled code, also some `ads.h` is refered. I assume you have this header and just use it to build the binary, but disable it for this repo. Did I get this right?

---

It would also be more honest to the user and developer to state *clearly* in the readme that this repository is not the same as the binaries you distribute.

I think a distinction should be made between the *binaries you distribute* and *this repository*. That would only be fair to the users and developers looking at this.

By the way, just to be clear: The binary version of this repo is this app, right?:
https://play.google.com/store/apps/details?id=mobi.MultiCraft

> MultiCraft has always been a completely open project. We publish all the source code, which was taken from other sources. But you are right in saying that some part is proprietary.

Sorry, this doesn't make sense. You can't have a *completely* open project if you admit 2 sentences later that “some part is proprietary”. These statements are mutually exclusive. If there are “some proprietary parts”, the software as a whole is not open source, not free software. So what exactly is now true?

If there are proprietary *anything*s in the repository, please show them (I'm curious).

> Also, some images and fonts we LICENSED for use EXCLUSIVELY in this project.

Sorry, but this sadly means this repository cannot be considered “open source” under the OSI definition. Open source also means the user (i.e. not you) is free to share the software (including media) freely.
Which is of course not the case if *only you* have a license to use, redistribute, change and share the changes of these files, but not your end users.
And yes, media is definitely to be considered to be a critical part of the game (no media = game does not work).

If you cannot or do not want not find replacements, that's fine, but then my only request is that you are at least being upfront about it and stop calling the game / this repository as a whole “open source”.

> Accordingly, we have the right to add these libraries by patch during the build process.

This is off-topic, I never claimed you were violating anyone's licenses nor anyone's copyright.
This is missing the point. The point is that I question the validity of the claims that this repo itself is open source.

> If someone wants to take all the changes to MultiCraft completely and create another project, he can write to us and I will indicate which images were purchased from which authors and he can buy permission for their use in his project.

I don't think this will be neccessary. Thanks for the offer, however.

So I summarize:

* You said this repo includes proprietary code, I'm still not sure where
* You also said this repo contains proprietary media as well
* The **readme** (!) states this repo includes proprietary code and resources
* On the other hand, you still claim this whole project is open source (which is clearly false, given the proprietary media)

**Comment by MoNTE48** [comment]
I agree that now there is some confusion! I will try to eliminate it for some time (really, I should have done it earlier! I regret it).
1) Binary files are not proprietary. However, they contain a proprietary code for advertisements. However, they are free for distribution.
2) All code located in this repository is free for modification and distribution, according to the license. I completely rewrote the entire Java part in this project and I could easily close it or add an extremely limited license, because now it's not a minetest code, but I do not. This is still LGPLv3 +!
Anyone has the right to distribute, modify and publish this code if the license is executed.
3) About the distribution of materials, I do not completely agree with you. Some of your code is open source, and it may be interesting for me. But I do not have the right to add it to my project! Do you know why? When you tell me the answer, you will understand that I am right.
Also, many products, for example LibreOffice, are open source projects. But if I do fork, delete the list of authors, call it Multi Office and start selling, I'll break a lot of laws. :) Although this is an open source product.
4) I will change the readme and make it clear that the binary files are not 100% relevant to the repository. I'll do it in a week. I will also start publishing binary files in the repository, not just Google Play.
---
I will sum up. Just like the various third-party modules that are used in Minetest, and in MultiCraft have different licenses, so media also has a license that does not allow it to be used in another project.
You can make a fork and use it for yourself, you can do an amateur build. But you must remove not free media if your project ceases to be called MultiCraft and you decide to publish it in any application store!

**Comment by appgurueu** [comment]
I agree with Wuzzy. It is open source, but only partially. Maybe call it a "partially open-source" project or an "open-source" inspired project ?

**Comment by MoNTE48** [comment]
@appgurueu all source code in this repository is licensed under LGPLv3+, MIT, BSD, WTFPL, or another open GPL-compatible license.

**Comment by appgurueu** [comment]
But the actual release contains proprietary parts ?

**Comment by MoNTE48** [comment]
No, it does not.  Only ios build contains the Appodeal ad library.

**Comment by MoNTE48** [comment]
For clarity. **MultiCraft is no longer published on Google Play.** All applications that use the source code MultiCraft or called MultiCraft are **unofficial**. I do not follow this.
This repository contains all source code, with the exception of the static Appodeal library and a few lines of code with identification and secret key (which are forbidden to be published for security reasons). The LGPLv3 permits this.
Instructions are available to build MC for any platform, following them you will get Linux, Windows, Android, iOS build in just a few steps. Without advertizing, without viruses.

**Comment by Lejo1** [comment]
And what about iOS? You know that you aren’t allowed to publish multicraft there, don’t you?

**Comment by MoNTE48** [comment]
Are you a lawyer?  Read the license.  If you can not understand, contact a lawyer, as I did.

**Comment by Lejo1** [comment]
The Problem are the iOS-Rules.
GPL is not Compatible with the App Store

**Comment by MoNTE48** [comment]
Right. That is why the entire GPL source code has been removed from MultiCraft. Everything in this repository is licensed as LGPLv3, MIT, BSD, WTFPL. All of them are fully compatible with the rules of the Apple App Store.

**Comment by Lejo1** [comment]
LGPLv3 is also included in GPL

**Comment by Minetest-One** [comment]
the server-list is NOT part of this rules and licence - the server-list is a other part, free and payed and so no need to look those, the owner of this list can do whatever is needed to protect the core and name of minetest.

**Comment by MoNTE48** [comment]
You're wrong. I close this question because it no longer makes sense. If you think that I am violating the license, then I invite you to court. I will be glad to win it :)

**Comment by Lejo1** [comment]
I not even need to I will just write Apple.

**Comment by Lejo1** [comment]
Ah before I forget it I prefer you to delete it yourself to save your developer account see here what’s the Problem:
https://stackoverflow.com/questions/8501685/ios-app-and-lgpl-issue
https://stackoverflow.com/questions/28803861/gpl-library-in-ios-app-without-open-sourcing
Just for you I told you!!!

**Comment by Wuzzy2** [comment]
So to clarify, MultiCraft is now, in fact, 100% open source?

If not, which are the parts that still aren't?

**Comment by MoNTE48** [comment]
All code in this repository is open source.
Some graphics are still proprietary (I bought the right to use only for one game. Buying full rights to the entire schedule would have cost several thousand dollars!)
When I building a game for iOS/Android, I copy the Appodeal ads and Google Analytics static library (proprietary, but LGPL compatible) and a patch is used to add the Google Service and Appodeal secret key.

**Comment by MoNTE48** [comment]
To be sure!
My right to use graphics allows others to fork and make changes as long as their game is used for personal purposes. 
But anyone can fork, replace graphics and do whatever he wants with the game under the LGPL license!

**Comment by Wuzzy2** [comment]
Sorry, but this means the claim on the readme is very misleading then. Nothing what you just told me is mentioned in this file.

This is not about bringing *you* to court (I am NOT claiming you are violating anyone's copyright), this is about protecting users from getting dragged to court for copyright violation because of misleading license notes.

The README does not warn the users that proprietary parts are included (only a vague “unless otherwise noted”). I explain why this is a problem: This will lead users right into the copyright trap. Believing they have an open source game, they might use and redistribute and alter this game at will (INCLUDING the graphics! Without the graphics, there's no game), because this is what open source means.

So the users will have a tough awakening when they are then sued for copyright infringement because they altered the graphics a bit or touched another file they were not supposed to touch and then shared it publicly (e.g. fork it on GitHub). Please at least warn the users about the potential risks.

Also: Please note that the definition of “open source” is not restricted to the source code: https://opensource.org/osd (from the people who invented the term “open source”, by the way).

**Comment by MoNTE48** [comment]
I understand what you mean! Yes, I'll do it. It’s really quite a tedious process, because I don’t remember the origin of each texture. I need to make a list, find a ton of email correspondence, check the personal accounts of various photo stocks, clarify usage rights from all individuals from whom I have ever bought graphics. It takes time.

**Comment by Wuzzy2** [comment]
If you don't know everything yet, you could just add a simple warning in the README for now and just write the things that you do know already. Can always add more detail later. Just to make it clear the game is only ***PARTIALLY*** open source right now.

Just a few sentences like “The graphics are NOT open source”. Or “The source code of this game is under an open source license but not the media files.” or whatever else best summarizes the current state of this project.

But I appreciate you are actually willing to go through all the work. Wow, that sure sounds painful to do …

**Comment by MoNTE48** [comment]
![Аннотация 2019-06-20 205728](https://user-images.githubusercontent.com/6764600/59874253-1badc680-939e-11e9-9185-006fdeb50811.jpg)

**Comment by Wuzzy2** [comment]
I'm afraid all I can do is refer you to the legal code …

https://creativecommons.org/licenses/by/3.0/legalcode
https://creativecommons.org/licenses/by/4.0/legalcode

IANAL, after all.

**Comment by Wuzzy2** [comment]
Oops, wrong links. Correct links:

https://creativecommons.org/licenses/by-sa/3.0/legalcode
https://creativecommons.org/licenses/by-sa/4.0/legalcode

**Comment by Wuzzy2** [comment]
I'm afraid all I can do is point you to the legal code …

https://creativecommons.org/licenses/by-sa/3.0/legalcode
https://creativecommons.org/licenses/by-sa/4.0/legalcode

IANAL, after all. There are more competent people to ask these kind of questions.
