### ISSUE TITLE
Missing nodes, incorrect mapgen aliases, broken biomes

### ISSUE THREAD

**Issue by paramat** [MultiCraftProject/MultiCraft#121]
Current nodes in https://github.com/MultiCraftProject/MultiCraft/tree/master/games/default (duplicates shown as (2)):

dirt with snow
snow (slab)
snowblock
ice

pine tree
pine wood
pine needles
pine sapling

stone
stone with coal
stone with iron
stone with gold
stone with bluestone
stone with lapis
stone with emerald
stone with diamond

stonebrick
stonebrickcarved
stonebrickcracked
stonebrickmossy

dirt with grass
dirt with grass footsteps
dirt with snow (2)
dirt

gravel
sand
sandstone
sandstonesmooth

redsand
redsandstone
redsandstonesmooth
redsandstonecarved

clay
brick
haybale

tree
wood
sapling
leaves
apple

jungletree
junglewood
jungleleaves
junglesapling

pine tree (2)
pine wood (2)
pine needles (2)
pine sapling (2)

acacia tree
acacia wood
acacia leaves
acacia sapling

junglegrass
cactus
papyrus
reeds

quartz ore
quartz block
quartz chiseled
quartz pillar

bedrock
bookshelf
slimeblock
glass

AddGlass( "Glass Red",  "basecolor_red", "_red")
AddGlass( "Glass Green",  "unicolor_dark_green", "_green")
AddGlass( "Glass Blue",  "basecolor_blue", "_blue")
AddGlass( "Glass Light Blue",  "basecolor_cyan", "_light_blue")
AddGlass( "Glass Black",  "basecolor_black", "_black")
AddGlass( "Glass White",  "basecolor_white", "_white")
AddGlass( "Glass Yellow",  "basecolor_yellow", "_yellow")
AddGlass( "Glass Brown",  "unicolor_dark_orange", "_brown")
AddGlass( "Glass Orange",  "excolor_orange", "_orange")
AddGlass( "Glass Pink",  "unicolor_light_red", "_pink")
AddGlass( "Glass Gray",  "unicolor_darkgrey", "_gray")
AddGlass( "Glass Lime",  "basecolor_green", "_lime")
AddGlass( "Glass Silver",  "basecolor_grey", "_silver")
AddGlass( "Glass Magenta",  "basecolor_magenta", "_magenta")
AddGlass( "Glass Purple", "excolor_violet", "_purple")

ladder
vine
wood (2)
cloud

water source
water flowing
river water source
river water flowing
lava source
lava flowing

torch
chest
chest left
chest right

cobble
mossycobble
steelblock
goldblock
diamondblock
lapisblock
emeraldblock
obsidian

apple (2)
apple gold
dry shrub
grass
glowstone
sponge
sponge wet

ice (2)
packedice
snow (2) (thinner slab)
snowblock (2)

////////////

Incorrect mapgen aliases:

desert stone -> redsandstone
desert sand -> redsand
sandstonebrick -> sandstone
stair_sandstonebrick -> stair_sandstone

////////////

Missing nodes found in decoration defs:

dry_grass (use one length, recolour texture)

////////////

Missing nodes found in biome defs:

Desert:
desert sand (use redsand)
desert stone (use redsandstone)

Savanna:
dirt with dry grass (recolour texture)

///////////

@MoNTE48 i can make a PR to fix all this, it will be quite easy.
For 'dirt_with_dry_grass' and 'dry_grass' (dry tall grass) i can make temporary textures by recolouring green grass textures.
Shall i do it?

**Comment by MoNTE48** [comment]
@paramat yes, please!
For 'dirt_with_grass' and 'dry_grass':
We have "default:dirt_with_grass" https://github.com/MultiCraftProject/MultiCraft/blob/master/games/default/files/default/textures/default_grass_side.png or is this not what you're talking about?
About "dry_grass" - I do not want to see this at the moment. This will be added to MultiCraft 1.2 later.
---
In my subgame everything is pretty confusing. It is based on overcraft and some other works, and I have not yet fixed all the problems

**Comment by paramat** [comment]
Ok will make a PR if you merge Mgv7p.
```
Missing nodes found in biome defs:
Savanna:
dirt with dry grass (recolour texture)
```
The missing node is 'dirt with DRY grass'

> About "dry_grass" - I do not want to see this at the moment.

Ok.

**Comment by paramat** [comment]
I wrote:
> For 'dirt_with_grass' and 'dry_grass' (dry tall grass) i can make temporary textures by recolouring green grass textures.

Oops sorry, that should be:
> For 'dirt_with_dry_grass' and 'dry_grass' (dry tall grass) i can make temporary textures by recolouring green grass textures.

**Comment by MoNTE48** [comment]
Ah, ok
I don't want to see 'dirt_with_dry_grass' and 'dry_grass' now

**Comment by paramat** [comment]
The savanna biome wil look weird without dry grass. But ok i'll give it green grass.

**Comment by MoNTE48** [comment]
@paramat we have default_dry_shrub
You can make default_dry_shrub alias dry_grass

**Comment by paramat** [comment]
PR #122

**Comment by MoNTE48** [comment]
I looked at your PR, everything seems fine.
Your idea about the savannah is absolutely correct, I agree with the addition of "dirt_with_dry_grass" and "dry_grass"
However, I would like that this does not affect the current version of the game and all existing mapgenv6 player worlds.
While we do not have a beautiful texture, I do not want to add "temporary textures" to my players.

**Comment by paramat** [comment]
Adding 'dirt_with_dry_grass' and 'sry_grass' won't affect existing mgv6 worlds because mgv6 doesn't have the savanna biome. The savanna biome is only in non-mgv6 mapgens.

**Comment by MoNTE48** [comment]
Good, please, do it

**Comment by paramat** [comment]
Will do very soon.

**Comment by MoNTE48** [comment]
@paramat now we can close this issue?

**Comment by paramat** [comment]
Yes, but ...
We still have some nodes registered twice in nodes.lua, see first post. Which ones do you want to use? Maybe you can delete the ones you don't want?
When a node is registered twice i'm not sure which registration is used. I'll test to find out and will let you know.
