### ISSUE TITLE
Can't compile sync branch on Linux

### ISSUE THREAD

**Issue by paramat** [MultiCraftProject/MultiCraft#138]
I reforked MultiCraft but compilation fails on 'sync' branch:
(the 'server' branch does not exist in my fork for some reason).
```
/MultiCraft/src/client.cpp: In member function
‘void Client::initLocalMapSaving(const Address&, const string&, bool)’:
/MultiCraft/src/client.cpp:782:18: error: expected type-specifier before ‘MapDatabaseSQLite3’
  m_localdb = new MapDatabaseSQLite3(world_path);
```
I suspect https://github.com/MultiCraftProject/MultiCraft/commit/a13e033c89c15692c56859756c1c6e9f78623670 may be the problem as it un-commented this section.
See https://github.com/MultiCraftProject/MultiCraft/commit/8a4933f707d121211b3507a7d7fb4c27ab0eb2b9 "Completely disable SQLite so it can be omitted" which commented this section.

**Comment by paramat** [comment]
Tried that, now it compiles.

**Comment by paramat** [comment]
Tested, reverting the changes made in client.cpp in https://github.com/MultiCraftProject/MultiCraft/commit/a13e033c89c15692c56859756c1c6e9f78623670 fixes the bug.

**Comment by MoNTE48** [comment]
Sync branch was removed as obsolete. Server branch was renamed to master!

**Comment by paramat** [comment]
Ok thanks, this issue is fixed in master then.
