### ISSUE TITLE
Please Mention Minetest

### ISSUE THREAD

**Issue by azekillDIABLO** [MultiCraftProject/MultiCraft#25]
Hello! I'm the admin of the "Minetest Copy Report"!
We would like you to add the following words to the description on app store and on github:`"This game is based on Minetest, by Celeron55"`. Since there are no license issues, just please add this! Thank you for your comprehension :+1:

**Comment by MoNTE48** [comment]
Hey. You can learn more about what is Minetest Copy Report? Thank you

**Comment by azekillDIABLO** [comment]
Minetest Copy report is a kind of league, which i created 1 month ago, to report and solve all the issues with licenses of minetest and to stop the expansion of abusive copies. Our forum is [HERE](https://forum.minetest.net/viewtopic.php?f=3&t=15147) and our GitHub Repo for report is [Here](https://github.com/azekillDIABLO/Minetest_Copy_Report)

**Comment by MoNTE48** [comment]
This is commendable, you're doing well. However, I am not sure what is required to specify Celeron55 (with all due respect to him) in the description in the play store, as well as any other contributor. However, I will point out that the game is based on Minetest. What do you say?

**Comment by azekillDIABLO** [comment]
there is no problem if you put a link to the minetest source code! Thank
you!

2016-07-31 10:54 GMT+02:00 Maksim Gamarnik <notifications@github.com>:

**Comment by MoNTE48** [comment]
All this is present here https://github.com/MultiCraftProject/MultiCraft/blob/master/README.md In addition, the license is not required to indicate the original source code, only the changes.

**Comment by azekillDIABLO** [comment]
ok great.

2016-07-31 11:05 GMT+02:00 Maksim Gamarnik <notifications@github.com>:
