### ISSUE TITLE
Prevent players from announcing to serverlist

### ISSUE THREAD

**Issue by sfan5** [MultiCraftProject/MultiCraft#27]
`xxx.xxx.xx.xxx - - [02/Oct/2016:13:00:55 +0000] "POST /announce HTTP/1.1" 202 61 "-" "MultiCraft/1.1.4--Android (Linux/3.0.31-1460734 armv7l)" "-"`
I get lots of those  on servers.minetest.net, but I have never seen a single MultiCraft server on the serverlist which means that 100% of announces are accidental (and don't even work).

My suggestion is to force `server_announce` to be off or at least not allow players to enable it from the menu.

**Comment by MoNTE48** [comment]
I do not quite understand you. I think you speak Russian?

**Comment by sfan5** [comment]
I don't.

The gist of it is that `server_announce` should be `false` when running on Android.

**Comment by MoNTE48** [comment]
This is the default value, but a player may change it.

**Comment by sfan5** [comment]
Then disallow the player from changing it, hosting servers on Android doesn't make sense.

**Comment by MoNTE48** [comment]
I can make a separate serverlist for android players, if you help

**Comment by sfan5** [comment]
No that isn't needed.

**Comment by MoNTE48** [comment]
What?

**Comment by sfan5** [comment]
You don't need a seperate serverlist for Android players.

The only thing you need is disable `server_announce` on android.

**Comment by MoNTE48** [comment]
okay, I will do it in the next update.
