### ISSUE TITLE
saving & world converting

### ISSUE THREAD

**Issue by andwan0** [MultiCraftProject/MultiCraft#43]
1. Can we have a save world button? For servers.

2. Also, can we have option to change from creative world to survival world?

3. Can we have "show in LAN" when we create server please.

4. Is there a PC desktop version to create server in?

**Comment by MoNTE48** [comment]
1. The world is saved automatically.
 2. There is a button in the menu. 
3. Not now. 
4. You can get a version for the PC in the releases section.

**Comment by andwan0** [comment]
thank you so much!
