### ISSUE TITLE
How to connect

### ISSUE THREAD

**Issue by noskcid7** [MultiCraftProject/MultiCraft#68]
My friend created his own his own server but I can't find it in multiplayer. My question is how do I connect to his server

**Comment by szymonweidler** [comment]
I know that many people get some issues to built this MultiCraft project. If you need my assistance to launch the project or develop new features write to me (szymonweidler@gmail.com). I will definitely help!

**Comment by LoneWolfHT** [comment]
@MoNTE48 How do I even get on multiplayer?

**Comment by MoNTE48** [comment]
What operating system?
