### ISSUE TITLE
Multicraft library

### ISSUE THREAD

**Issue by Olexandr1904** [MultiCraftProject/MultiCraft#72]
Where I can find  multicraft library and others librarys which needed to start the android app?System.loadLibrary("multicraft");

**Comment by MoNTE48** [comment]
Hey. They are in the build/Android/libs folder

**Comment by Olexandr1904** [comment]
Thanks for your fast answer. unfortunately I can't find libs folder in the repository or in the my project folder. Maybe it because I didn't Execute "make" (like in readme debug build) But I don't see "make" in the repository only "makefile". And honestly I can't understand how I can execute this. Is it likely for Linux system?

**Comment by MoNTE48** [comment]
You need a Linux distribution. Pls, read the readme, the "Build" section, "Release build".
