### ISSUE TITLE
Can't play MulltiCraft on desktop (is it possible?)

### ISSUE THREAD

**Issue by paramat** [MultiCraftProject/MultiCraft#82]
I can compile but when running game instantly crashes:
```2017-07-19 19:21:17: WARNING[Main]: Couldn't find a locale directory!
2017-07-19 19:21:17: ERROR[Main]: GUIEngine: execution of menu script failed: Failed to load and run script from /MultiCraft/bin/../builtin/init.lua:
2017-07-19 19:21:17: ERROR[Main]: /MultiCraft/bin/../builtin/mainmenu/tab_credits.lua:1: unexpected symbol near '�'
2017-07-19 19:21:17: ERROR[Main]: stack traceback:
2017-07-19 19:21:17: ERROR[Main]: 	[C]: in function 'dofile'
2017-07-19 19:21:17: ERROR[Main]: 	/MultiCraft/bin/../builtin/mainmenu/init.lua:53: in main chunk
2017-07-19 19:21:17: ERROR[Main]: 	[C]: in function 'dofile'
2017-07-19 19:21:17: ERROR[Main]: 	/MultiCraft/bin/../builtin/init.lua:45: in main chunk
2017-07-19 19:21:17: ERROR[Main]: No future without main menu!
Aborted (core dumped)
```
@sfan5 anything i need to to do to run MultiCraft on desktop? I compiled it just like MT.

**Comment by MoNTE48** [comment]
My mistake. I forgot to send fixes to main_menu after update MultiCraft.
Will you try to check again?
https://github.com/MultiCraftProject/MultiCraft/commit/4d948c4b9c9f80d6bd14dc760f2b30f4d28eaa56

**Comment by paramat** [comment]
Better, i can start the game, but when entering a world i get:
`2017-07-19 23:05:12: ERROR[Main]: Some exception: "Database backend leveldb not supported."`
I will recompile with a different database backend and try again.

**Comment by paramat** [comment]
I tried:
`cmake . -DRUN_IN_PLACE=1 -DENABLE_LEVELDB=0`
and 
`cmake . -DRUN_IN_PLACE=1 -DENABLE_LEVELDB=1`
but same problem, menu works but when entering a new world i get instantly returned to main menu with that message.

**Comment by MoNTE48** [comment]
Hmm. @sfan5 up!

**Comment by paramat** [comment]
Ok this might work:
cmake . -DRUN_IN_PLACE=1 -DENABLE_LEVELDB=1 -DLEVELDB_INCLUDE_DIR -DLEVELDB_LIBRARY
Will try.

**Comment by paramat** [comment]
No.
```In file included from .../MultiCraft/src/database-leveldb.cpp:24:0:
.../MultiCraft/src/database-leveldb.h:29:24: fatal error: leveldb/db.h: No such file or directory
compilation terminated.
src/CMakeFiles/MultiCraft.dir/build.make:2990: recipe for target 'src/CMakeFiles/MultiCraft.dir/database-leveldb.cpp.o' failed
make[2]: *** [src/CMakeFiles/MultiCraft.dir/database-leveldb.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:272: recipe for target 'src/CMakeFiles/MultiCraft.dir/all' failed
make[1]: *** [src/CMakeFiles/MultiCraft.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by paramat** [comment]
Ok i can play in worlds now by adding this to the 'world.mt' file:
`backend = sqlite3`
