### ISSUE TITLE
Simplification of ore registrations?

### ISSUE THREAD

**Issue by paramat** [MultiCraftProject/MultiCraft#87]
I see you have 2 or 3 ore registrations for each ore. I can slightly speed up mapgen if i combine the registrations for each ore into 1 registration, let me know if you agree to this.
If i do this i can calculate the exact equivalent so that amount of each ore does not change.

At the same time i can make glowstone lower to not be seen so often in deep ocean, how low would you like it to be?

**Comment by MoNTE48** [comment]
@paramat, about simplification of ore registrations: This is a great idea! I'll be glad if you do it.
The light stone is at the optimum height, it seems to me. Maybe I'll decide to lower it below in the future. But not now.

**Comment by paramat** [comment]
Ok.

**Comment by paramat** [comment]
@MoNTE48 i am happy to do this, but i need to know which 'default game' you want this done in.
I recommend starting again by forking Minetest Game 0.4.16.

**Comment by MoNTE48** [comment]
@paramat I tried to update mapgen to the latest version of minetest_game (master), taking into account those available in the MultiCraft API.  Could you look at the last commit in the server branch?
 I also need help with the separation of sand and redsand.
